#!/bin/sh
set -e

if [ "$1" = "configure" ] ; then
	update-alternatives --quiet --install /usr/bin/x-www-browser x-www-browser \
		/usr/bin/dillo 30 \
                --slave /usr/share/man/man1/x-www-browser.1.gz x-www-browser.1.gz \
	        /usr/share/man/man1/dillo.1.gz
fi

# Automatically added by dh_installmenu/13.2~bpo10+1
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section

