#!/bin/sh

set -e

case "${1}" in
	remove|upgrade|deconfigure)
		update-alternatives --remove x-session-manager /usr/bin/lxsession
		;;

	failed-upgrade)

		;;

	*)
		echo "prerm called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

# Automatically added by dh_installdeb/12.1.1
dpkg-maintscript-helper rm_conffile /etc/xdg/autostart/lxpolkit.desktop 0.5.3-1 lxsession -- "$@"
# End automatically added section


exit 0
