#!/bin/sh

set -e

if [ "$1" = configure ]
then
	for exe in /usr/share/docutils/scripts/python3/*
	do
		update-alternatives --install /usr/bin/${exe##*/} ${exe##*/} $exe 20
	done
fi


# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p python3-docutils 
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p python3-docutils  || true
fi

# End automatically added section

