# This file was generated by ecm_install_qch_export(). DO NOT EDIT!

if (NOT TARGET KF5BluezQt_QCH)

add_custom_target(KF5BluezQt_QCH)
set_target_properties(KF5BluezQt_QCH PROPERTIES
    DOXYGEN_TAGFILE "/usr/share/qt5/doc/KF5BluezQt.tags"
    QHP_NAMESPACE "org.kde.BluezQt"
    QHP_NAMESPACE_VERSIONED "org.kde.BluezQt.5_54_0"
    QHP_VIRTUALFOLDER "bluezqt"
    IMPORTED TRUE
)
set_property(TARGET KF5BluezQt_QCH PROPERTY LINK_QCHS Qt5Core_QCH)

endif()
